services:
  - type: web
    name: memecoin-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_TO
        sync: false

  - type: worker
    name: memecoin-bot-scanner
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python worker.py"
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_TO
        sync: false